version: "3.5"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: jK2XORavWC8fL3b41jjqnD316ROe
      MYSQL_DATABASE: restestdb
      MYSQL_USER: lasileuka
      MYSQL_PASSWORD: E7IBKyBOu5UBGVDq1V9hn6ZEjK2s
    ports:
      - 7306:3306
    volumes:
      - mysqldata:/var/lib/mysql/data

  php:
    image: drupal:8.5-fpm
    environment:
      DB_HOST: mariadb
      DB_USER: lasileuka
      DB_PASSWORD: E7IBKyBOu5UBGVDq1V9hn6ZEjK2s
      DB_NAME: restestdb
      DB_DRIVER: mysql
    links:
      - mariadb:mysql
    volumes:
      - drupal-install:/var/www/html

  nginx:
    image: nginx:latest
    links:
      - php
    ports:
      - '7080:80'
    volumes:
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - drupal-install:/var/www/html
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html

volumes:
  mysqldata: {}
  drupal-install: {}