version: "3.6"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: restestdb
      MYSQL_USER: lasileuka
      MYSQL_PASSWORD: /run/secrets/db_password
    ports:
      - 7306:3306
    volumes:
      - mysqldata:/var/lib/mysql/data

  php:
    image: drupal:8.5-fpm
    environment:
      DB_HOST: mariadb
      DB_USER: lasileuka
      DB_PASSWORD: /run/secrets/drupal_password
      DB_NAME: restestdb
      DB_DRIVER: mysql
    links:
      - mariadb:mysql
    volumes:
      - drupal-install:/var/www/html

  nginx:
    image: nginx:latest
    links:
      - php
    ports:
      - '7080:80'
    volumes:
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - drupal-install:/var/www/html
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
  drupal_password:
    file: drupal_password.txt

volumes:
  mysqldata: {}
  drupal-install: {}